# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          ./pack.sh buster
		      echo "::set-output name=status::success"

      - name: Upload firmware
	      if: steps.compile.outputs.status == 'success'
          with:
		      name: armbian.tar.xz
		      path: Build-Armbian
          
     	- name: Generate release tag
        id: tag
        if: steps.compile.outputs.status == 'success'
        run: |
          echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
          touch release.txt
          echo "🔗 [Cowtransfer](${{ steps.cowtransfer.outputs.url }})" >> release.
          echo "🔗 [WeTransfer](${{ steps.wetransfer.outputs.url }})" >> release.
          echo "FIRMWARE=Build-Armbian/armbian.tar.xz" >> $GITHUB_ENV
          echo "::set-output name=status::success"

      - name: Upload firmware to release
        uses: softprops/action-gh-release@v1
        if: steps.tag.outputs.status == 'success' && !cancelled()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body_path: release.txt
          files: ${{ env.FIRMWARE }}/*

      - name: Delete workflow runs
        uses: ActionsRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 3
         
          
